# Generated by Django 6.0.2 on 2026-02-17 03:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_homepage_and_page_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, help_text='Imágenes del carrusel (debajo de las pestañas).'),
        ),
    ]
