# Generated by Django 6.0.2 on 2026-02-19 11:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_homepage_carousel'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('periodo', models.CharField(blank=True, help_text='Ej: 2025-actualidad, 2004-2025, 1995-2003', max_length=100)),
                ('descripcion', wagtail.fields.RichTextField(blank=True, help_text='Breve reseña o cargo.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='0 = obispo actual (se muestra primero). Mayores = anteriores.')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Autoridad (Obispo)',
                'verbose_name_plural': 'Autoridades (Obispos)',
                'ordering': ['orden'],
            },
        ),
    ]
