# Generated by Django 6.0.2 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_autoridad_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesiapage',
            name='intranet_id',
            field=models.IntegerField(blank=True, help_text='ID en la intranet; usado al sincronizar con la API para actualizar esta ficha.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mapapage',
            name='iframe_url',
            field=models.URLField(blank=True, help_text='URL de la app del mapa (ej. imparg.org/.../mapa). Si está vacío, se muestra el mapa de iglesias con Leaflet.', verbose_name='URL del iframe del mapa'),
        ),
    ]
