# Generated by Django 6.0.2 on 2026-03-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contacto_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='noticiapage',
            name='url_imagen_fb',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
